### ISSUE TITLE
MSys2 Build Error

### ISSUE THREAD

**Issue by Haafingar** [monero-project/monero-gui#1135]
Followed instructions on the README verbatum, not sure if this has something to do with the latest commits to Monero.

```
C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lwallet_merged
C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lepee
C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lunbound
C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -leasylogging
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile.Release:202: release/bin/monero-wallet-gui.exe] Error 1
make[1]: Leaving directory '/home/Rig/monero-gui/build'
make: *** [Makefile:36: release] Error 2
```

Attached is the full output. Running Qt 5.9.4, boost 1.63.0
[Buildlog.txt](https://github.com/monero-project/monero-gui/files/1753642/Buildlog.txt)

**Comment by yagamidev** [comment]
Faced that issue too. 
The problem is on the README for now.
The thing is that when you follow instructions of the readme you install twice the boost library 
by this command 
`pacman -S mingw-w64-i686-toolchain make mingw-w64-i686-cmake mingw-w64-i686-boost mingw-w64-i686-openssl mingw-w64-i686-zeromq mingw-w64-i686-libsodium`

And by the one downloaded from sourceforge. But the one downloaded from  sourceforge isn't used I don't know why yet. 

The boost you download with the command install the latest version of boost which is "1.66" if I don't get wrong, and you have cmake3.10 which doesn't support the latest version of boost yet. 
So to fix the issue, uninstall the mys env and reinstall it but now not including boost in the command, so you should run 
`pacman -S mingw-w64-i686-toolchain make mingw-w64-i686-cmake mingw-w64-i686-openssl mingw-w64-i686-zeromq mingw-w64-i686-libsodium`
and keep compiling the one downloaded from sourceforge.

**Comment by yagamidev** [comment]
The problem starts from here `mingw32-make: Leaving directory 'C:/msys32/home/Rig/monero-gui/monero`
Seems like there is an issue with the submodule.
What you can try yo do is trying compiling the Monero submodule first alone if it doesn't compile then the problem is coming from there.

**Comment by pazos** [comment]
I'm in for testing. The error is during linking and seems related to #1139 (osx) and #1078 (linux).

**Comment by pazos** [comment]
The README for windows is broken.We need to merge PRs #828 (update boost) and #1113 (Compile with stack protector).

Qt installation instructions should be simplified.

**Comment by danrmiller** [comment]
The monero daemon portion will not build on windows until this issue https://github.com/monero-project/monero/issues/3296 is resolved.

**Comment by danrmiller** [comment]
Yes.

+resolved
