### ISSUE TITLE
Dynamic embedded version recognition

### ISSUE THREAD

**Issue by leafcutterant** [monero-project/monero-gui#1238]
I updated the Monero binaries used by the GUI to 0.12, but it still displays the old version number in Settings -> Debug info.

I propose it not to be a static piece of text but actually checking the Monero version in the background and display the version properly.

**Comment by pazos** [comment]
I think you're mixing monerod version with the api version . Replacing monerod does not affect the gui, since it was built against a specific api and this api does not change until you replace monero-wallet-gui too. The api is part of the main monero repo.

This is debug info obtained at build time. monero version matches the api & monerod bundled with the software, so it's ok for me.

**Comment by leafcutterant** [comment]
GUI releases are very sparse in time, so manually updating monerod used by the GUI makes sense.

If indeed this doesn't change the functioning of the GUI client, then feel free to close the issue.

**Comment by skftn** [comment]
+resolved
