### ISSUE TITLE
GUI 12.0 missing cmd line box in "Status" window

### ISSUE THREAD

**Issue by BigslimVdub** [monero-project/monero-gui#1278]
This box was there in 11.* versions but is missing from 12.0. 
It is on aeon rebase 1.7.2 so unsure what happened there unless xmr devs took it out for 12.0? 

![xmr 12_0 missing cmd line box](https://user-images.githubusercontent.com/30030687/38398773-b13f8768-390b-11e8-8021-8d6960ab4dcc.png)
![aeon 1_7_2 cmd line box](https://user-images.githubusercontent.com/30030687/38398789-c40d1ca2-390b-11e8-952e-e9f970b4c97d.png)

**Comment by dEBRUYNE-1** [comment]
+bug

**Comment by Coded-Dude** [comment]
The box still exists, and you can interact with it(you should get the windows text/font cursor when you mouse over where the box should be), but for some reason the CMD font is white(or otherwise invisible) unless you highlight it.  I am able to enter commands and get reports/feedback.

![cli_bugjpg](https://user-images.githubusercontent.com/19971145/38430186-281651d0-3986-11e8-84ca-ac257bb9e8b9.jpg)

**Comment by BigslimVdub** [comment]
Completely blank on high Sierra. I do not get the cursor change. I have not tried on windows 10 yet.

**Comment by skftn** [comment]
#1292

**Comment by jamescanningcooke** [comment]
It’s there but invisible. Click

**Comment by guifalci** [comment]
is not there on Mac High Sierra....
