### ISSUE TITLE
GUI WALLET does not create blockchain

### ISSUE THREAD

**Issue by lukebook** [monero-project/monero-gui#1307]
I send the coin from the GUI WALLET to another account but I can't receive the coin.
Even I can not check the TX ID in a blockchain.
GUI WALLET  signify the coin is already sent and i can not see the coin in GUI WALLET.
Please help me.

![kakaotalk_20180411_084706657](https://user-images.githubusercontent.com/38267080/38589842-898ee8d8-3d68-11e8-9542-c64fa778d864.png)

**Comment by skftn** [comment]
Looks like the transaction is still `PENDING`. At this time of writing, current block height is `1548797`. If it still says `PENDING`, after 11 hours, I would guess you're having trouble connecting to the network, or, there is a bug that is preventing you from transfering funds.

Could you verify your transaction is still pending as of now?

**Comment by dEBRUYNE-1** [comment]
@lukebook:

You're probably on the wrong (alternative) chain. Therefore, you should be able to resolve your issue with this guide:

https://monero.stackexchange.com/questions/7993/i-forgot-to-upgrade-from-cli-or-gui-v0-11-to-cli-or-gui-v0-12-and-created-pe/

Please note (from the [linked guide](https://monero.stackexchange.com/questions/7989/i-forgot-to-upgrade-from-cli-or-gui-v0-11-to-cli-or-gui-v0-12-and-as-a-result)):

>As a general rule of thumb, for each day you synced after the fork height (1546000 or April 6) you have to pop 800 blocks. Thus, let's say you synced 10 days on the wrong (alternative) chain, you should use --pop-blocks 8000

Since we're 5 days after the scheduled network upgrade, you ought to use `--pop-blocks 4800`

**Comment by skftn** [comment]
+resolved
