### ISSUE TITLE
'ctrl-a' shortcut conflict

### ISSUE THREAD

**Issue by 1337tester** [monero-project/monero-gui#1374]
**Problem**
This shortcut is used for selection of the whole text on the cursor location, using it also for Shared RingDB tab is leading to confusion for users trying to select the whole string in some field (they suddenly find themselves in a completely different tab -> at least my case initially)

**Solution**
Assign some other shortcut for for Shared RingDB tab (anything that does not collide with some commonly used OS shortcuts)

**Comment by pazos** [comment]
I will go for rewrite the 'ctrl+tab' logic too, because seems random. The logic order would be Transfer->adressbook->Receive->Advanced-tabs->Options. I would skip the seeds page because I think it would stop the workflow asking for a password.

Any suggestion for an alternative to 'ctrl+a' to switch to Shared Ring DB? I can include that fix too.

**Comment by dEBRUYNE-1** [comment]
+resolved
