### ISSUE TITLE
[WIP] Restyle wizards to black-theme

### ISSUE THREAD

**Issue by xmrdsc** [monero-project/monero-gui#1513]
As the title says.

Fixes #746

+enhancement

#### ideas/to-do's

```
< knueffelbund> Is it possible to pick up the language from the OS setting?
< knueffelbund> Just as a default, but it could help some people avoid using this super long  menu.
```

**Comment by skftn** [comment]
Language selection screen:

![](https://i.imgur.com/9LJJU3Z.png)
![](https://i.imgur.com/jtg2DU9.png)

**Comment by Electricsheep01** [comment]
Very nice!

**Comment by skftn** [comment]
Home screen:

![](https://i.imgur.com/7QXQ14c.png)

**Comment by GBKS** [comment]
![monero-onboarding-type-icons-180806-2](https://user-images.githubusercontent.com/695901/43709387-f9200384-996c-11e8-9981-5d981dee87de.png)

Here's my current exploration for these icons. I'm talking to rehrar and tficharmers about some details (mostly color related), and also running it past some other designers I know to get an outside perspective. All feedback appreciated, as always.

**Comment by Leza89** [comment]
@ GBKS I like the `Create a new wallet` symbol you came with up since it's more descriptive of the action 
 but I prefer the old style in general tbh.

**Comment by GBKS** [comment]
@Leza89 thanks for the feedback. What do you like better about the old style?

**Comment by Leza89** [comment]
It doesn't look "modernized" - in general I don't like the new simplified designs. i.e.:

http://d5vf6134d8ffdnfp1qv4rv3l.wpengine.netdna-cdn.com/wp-content/uploads/04a-windows-os-logos.jpg

In chronological order:
1985: Ohgodwhy
1992-1994: too simple and flat
1995-2000: ok-ish
2001-2005: good
2006-2008: nice
2009-2012: nice
current: too simple and flat

(next: Ohgodwhy? ^^)

I guess I don't like the lack of a third color within the icon's borders and the mnemonic seed symbol looks quite similar to ledger and usb sticks. What's that supposed to represent?

**Comment by vp1111** [comment]
I like the language selection screen, but I believe the languages should be shown in alphabetic order.
The home screen looks nice, from the two images shared in the issue I prefer the _first one_. I have a couple things to say about both, but first things first: how are these designs going to work with the discussion ongoing on #1846? If we're going to have a screen between the `Language selection` and the `Setup your wallet` then it would also be nice to have a proposal for this new screen.

Design from @xmrdsc 
I think we could use different icons for `Create a new wallet`. A light bulb always comes up to me as "idea" instead of calling to the action of creation; I personally prefer the plus icon from the second design. Another one that could use a different icon is `Open a wallet from file`, I think it's too similar to the hardware wallet icon. File is usually represented by a _folder_ or a floppy disk. Maybe something like [this](https://image.flaticon.com/icons/svg/148/148957.svg), but with the Monero logo stamp on the paper.
I also think the `Language selection` button on the welcome screen could be bigger, more similar to like what is in the second design.

Design from @GBKS 
The icon for `Restore from keys or mnemonic` really makes me think about [LastPass button](http://blog.ryansjohnson.com/wp-content/uploads/2018/01/lastpass.png). The colors would probably have to be worked on as well, but you already mentioned that yourself so it's good. Same as the first design, I think `Open a wallet from file` should be something other than the USB stick.
I like `Previous / Next` buttons at the end although there's not really a "next" since the user has to click in one of the icons to actually proceed. I think the `Previous` button could also show the title of the previous screen (e.g. `Previous: Select wallet mode`)

**Comment by GBKS** [comment]
[Here's an updated design](https://www.dropbox.com/s/9658ioljjvjhh6d/monero-onboarding-how-to-set-up-gbks-191114.png?dl=0) based on the Reddit and IRC discussions. It uses the new icons in orange as requested, with an updated "Restore from file" icon (folder vs. USB stick).

However, I made them smaller and changed the layout from the horizontal list with big icons, to a vertical list with smaller icons and more text (a layout we already use for node selection). Having more text vs. just a short label makes it easier to explain what each options means, which will hopefully reduce confusion (text in the design is not final, I'd need help getting that perfect).

What do you think?

**Comment by GBKS** [comment]
@xmrdsc it is now - [see here](https://zpl.io/25qP4jo). Icons should be exportable in 1x (60x60px) and 2x (120x120px).

One more note that I did not adjust the saturation. Since the icons are smaller than in the previous layout, they are visually not as overwhelming. But let me know if there are still any other changes you'd like to see.

**Comment by xmrdsc** [comment]
Cheers. See #1909 for PR.
