### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by CokeBear** [monero-project/monero-gui#1735]
on Mac OS 10.14 
boost 1.68
![image](https://user-images.githubusercontent.com/6119459/48333947-17952a00-e694-11e8-8f17-ccebc3d44269.png)

**Comment by skftn** [comment]
Stuff I was able to find:

https://qiita.com/misho/items/0c0b3ca25bb8f62aa681
https://stackoverflow.com/a/28119190
https://github.com/litecoin-project/litecoin/issues/170
https://github.com/bitcoin/bitcoin/issues/3228

Solution probably is to reinstall boost.

**Comment by BigslimVdub** [comment]
I just compiled monero with git checkout v0.13.0.4 today on 10.13.6 no issues. I do however get this issue compiling Aeon. 

You can reinstall all dependencies with 

```
brew reinstall gcc boost --c++11 openssl pkgconfig cmake zeromq libsodium libusb unbound libunwind-headers xz ldns pcsc-lite miniupnpc readline expat libgtest doxygen graphviz hidapi qt5
```

Also after that, don't forget to clean up old installs with:

```
brew cleanup
```

Latest QT on osx is 5.11.2_1

Don't forget to link QT with this (if installed via brew)

```
export PATH=$PATH:$/usr/local/Cellar/qt/5.11.2_1
```

let me know if this works for you on mojave 10.14. I have held off upgrading since there were many brew issues about mojave.

**Comment by dEBRUYNE-1** [comment]
@CokeBear - Did you manage to resolve this particular issue?

**Comment by dEBRUYNE-1** [comment]
Author has not responded and therefore I am going to close this issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
