### ISSUE TITLE
HTML injection in "Receive" tab.

### ISSUE THREAD

**Issue by serhack** [monero-project/monero-gui#1799]
Version: Monero 0.13.0.4 GUI
Topic: Any users could inject HTML via the Receive page input fields "Set the label of new address" and "Edit the label". 

Steps to reproduce:

- Press "Create a new address" link
- Insert your HTML
- Voilà, your HTML is displayed 

In every security model I see, there's a MUST: parse any inputs from the user. I would like to apply this to Monero GUI too. It seems in some places HTML injection is not possible, but I would like to run more tests.

(However, this is not a security issue).

**Comment by xmrdsc** [comment]
Thanks. This is due to how the `textFormat` property of QML Type `Text` defaults to `Text.AutoText` - which  according to the documentation will turn the component into RichText mode depending on the content. 

> If the text format is Text.AutoText the Text item will automatically determine whether the text should be treated as styled text.

Solution is to default them to `textFormat.Text.PlainText` instead and use `RichText` only when needed. 

`MoneroComponents.Label`, which internally uses `Text`, is used in a lot of places so Ill check them all and PR a fix.
