### ISSUE TITLE
Not all language fields are updated after selecting a new language with flag icon

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2004]
If you select a new language on flag icon, almost all fields are updated to the new language, but some aren't.

**Comment by dEBRUYNE-1** [comment]
This may simply be due to incomplete translations. Pinging @erciccione.

**Comment by rating89us** [comment]
No, this is happening when I change from my native language back to english (which is the default).

**Comment by dEBRUYNE-1** [comment]
Interesting, definitely a bug then. 

+bug

**Comment by mmbyday** [comment]
@rating89us  Without knowing exactly what fields you're referring to, I submitted PR #2016 that might fix some of the issues you're seeing. HTH. Please let us know if this fixes it. Thanks.

**Comment by xmrdsc** [comment]
@rating89us Does this still happen on the latest release?

**Comment by rating89us** [comment]
Sorry, I can't test it now.

**Comment by GBKS** [comment]
This issue came up in user testing on March 27. Right on the initial welcome screen, the button labels don't update then you pick a different language. So "Language" stays "Language", and "Continue" stays "Continue", even if you pick German or something else. That caused users to think the language selector was broken. Totally understandable if some things don't translate because of missing Strings, but would be cool to fix this particular issue so it doesn't feel broken.

**Comment by selsta** [comment]
This should be solved since #2088.

**Comment by erciccione** [comment]
My build fails, so i cannot test this, but as selsta says, it should be solved. Maybe @xmrdsc will have a second to check if it's solved.

**Comment by selsta** [comment]
+resolved
