### ISSUE TITLE
The "Receive" tab format gives an address that doesn't fit the "Spend" tab format

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-gui#2359]
![image](https://user-images.githubusercontent.com/32943174/63641477-24ac6400-c67d-11e9-82ac-a1d4d1a1c3ea.png)

The button here gives an output that looks like this: `monero:49dpgSbHdA6auSv2gMPEsfj3uXVqqon4LEGWpuhdfXJsULVLKjFXkFQhpywAU8WddGbsN2ZDDpiVb8byZH6FfgL2R7ZwKZE`

If you paste this in the send tab, it looks like this:

![image](https://user-images.githubusercontent.com/32943174/63641482-3aba2480-c67d-11e9-81f0-69c0e5a826ab.png)

And it's not a valid address.

**Comment by Realchacal** [comment]
Thanks for taking the time to write this issue and sorry for your troubles. You have to delete `monero:` at the beginning of the address or use the copy icon next to the address:
![image](https://user-images.githubusercontent.com/46682965/63648079-b7570c80-c72a-11e9-9556-c9ddd80fd06a.png)


**Proposal:**
- Let's use the correct icon:
![image](https://user-images.githubusercontent.com/46682965/63648240-1a49a300-c72d-11e9-9d5e-89b6d1079982.png)
(A [Google image search](https://www.google.com/search?q=copy+icon&tbm=isch) shows that this is the correct icon.)
- Auto-delete `monero:` if somebody pastes it in the address field on the `Send` page.

**Comment by Realchacal** [comment]
You have to delete `monero:` at the beginning of the address, or use the copy icon next to the address:
![image](https://user-images.githubusercontent.com/46682965/63648079-b7570c80-c72a-11e9-9556-c9ddd80fd06a.png)

But your issue shows what problems average users may have. Therefore, following **proposal**:
- Let's use an intuitive copy icon (instead of 2 different, unintuitive ones):
![image](https://user-images.githubusercontent.com/46682965/63648240-1a49a300-c72d-11e9-9d5e-89b6d1079982.png)
A [Google image search](https://www.google.com/search?q=copy+icon&tbm=isch) suggests that this is actually much more intuitive.
- When clicking on the copy icon below the QR code, it shouldn't say `Copied to clipboard`, it should say `QR code copied to clipboard as text (Monero URI format)` because a user may falsely expect that the address or the image is copied. (The latter is not far-fetched because for example the download button would download the image and not a text file.) Also, it gives the user a term he can web-search for (Monero URI format).
- When pasting something on the `Send` page into the address field that is not a valid address, **EITHER** don't change it at all **OR** extract the address if a valid URI string was pasted. Currently, when you paste a URI string, `:` is auto-deleted but `monero` is kept. IMO this is horrible **and super dangerous**! Because the user does not know what is actually happening and may stay unaware of the real mistake he is doing!
- Currently, a user gets the visual impression that the most important options on the `Receive` page are the QR code options, while the actual most important option ("Copy address") is easy to be overlooked completely. More intuitive:
![image](https://user-images.githubusercontent.com/46682965/63649636-415da000-c740-11e9-9278-97b218c5579f.png)

**Comment by xiphon** [comment]
> If you paste this in the send tab, it looks like this:
> 
> And it's not a valid address.

Yep, is a bug with address pasting using keyboard shortcuts. 
Use "paste" button, it will handle this correctly.
