### ISSUE TITLE
[Feature] [GUI] Make using Tor Easier

### ISSUE THREAD

**Issue by ggg27** [monero-project/monero-gui#2369]
**Feature**: Make enabling TOR simple
**What do you mean?**: The current process to enable TOR is bloated:
https://github.com/monero-project/monero#using-tor
I highly doubt I could get anybody to execute this. It is just too many steps.

**Possible Solution**:
I propose a GUI-only solution.
Similar to how Electrum executes this:
![Electrum-tor-enabled](https://steemitimages.com/p/3jpR3paJ37V8t3d5gG8YxUrFtTrvhgCDjjN8jFs76SdAZzuL8uVJXZwCVyow5zrJLhZu8giozzG54Nxd3mKUGCM8PQuBNAj3Zfykb62N6jhbCPS8F4jKNhfPBdANGDxfrGbWe?format=match&mode=fit&width=640)
___________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/79731168-feature-gui-make-using-tor-easier)! We accept Bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by maogo** [comment]
Yes, Electrum is very easy to use and intuitive interface.

**Comment by erciccione** [comment]
The integration of i2p/Tor in the GUI is in progress and will probably be included in next release of the wallet (WIP pic by @xmrdsc: https://i.imgur.com/ZUZknxB.png).

Also, see conversation in #2274 and a more recent one on reddit: https://old.reddit.com/r/Monero/comments/cva56q/does_monerogui_have_built_in_support_for_proxy/

Closing this, since the feature is work in progress and #2274 can be used to post updates about the development.

+duplicate

**Comment by jonathancross** [comment]
Personally, I kinda like the simple, straight-forward approach presented here (as in Electrum)
I'm concerned that #2274 might be getting overly complex.
