### ISSUE TITLE
Settings > Node: missing verb in options

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2653]
To be consistent with the remaining items in Settings page, we should add "Use" in options:
* Use local node
* Use remote node

Current:
![image](https://user-images.githubusercontent.com/45968869/71264968-fdf8f400-2323-11ea-8356-f72a6b094013.png)

**Comment by SamsungGalaxyPlayer** [comment]
I'm mostly indifferent about this one. No strong preference.

**Comment by erciccione** [comment]
@rating89us Please keep in mind that even if we are adding one single word, translators will have to retranslate the string in more than 30 languages. We should change strings only if the difference worth the effort (and the risk of having that string not translated in multiple languages).

In this case would be better to leave these two strings as they are, since the improvement is extremely minor.

**Comment by selsta** [comment]
Closing this one as I don't see consensus if favor if this change, also I personally think the current strings are nicer.
