### ISSUE TITLE
*BSD build instructions?

### ISSUE THREAD

**Issue by dchmelik** [monero-project/monero-gui#3034]
I see *BSD mentioned in the source code, but no instructions.  How would you build it on *BSD, such as FreeBSD 13-CURRENT?

**Comment by selsta** [comment]
I don’t think there are any instructions currently.

**Comment by selsta** [comment]
None of the contributors use *BSD, so I will close this. If someone is able to build it I would appreciate a PR with instructions :)

**Comment by theoden8** [comment]
Using clang-13 on FreeBSD 13.1-RELEASE. Building master (v0.17.3.2)

Install these packages:

```
pkg install git cmake ccache boost-libs libzmq3 qt5 protobuf libsodium protobuf
```

* If it doesn't find `zmq_send_const`, change it to `zmq_send`.
* If it complains about `el::base::debug::StackTrace` linkage errors referenced from `monero/src/common/stack_trace.cpp`-related object, make sure `monero/external/easylogging++/ea_config.h` defines `ELPP_FEATURE_CRASH_LOG`, otherwise `easylogging++.cpp` file won't compile implementations of most of its functions.

A party to make a PR would have to think through the above two problems in a bit more detail.
