### ISSUE TITLE
Error when opening mainnet wallet when Monero GUI is starting in stagenet mode

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#3818]
Steps to reproduce:
- Open a mainnet wallet
- Close the wallet and return to main menu
- In advanced options, choose stagenet in network type
- Close Monero GUI
- Reopen Monero GUI
- Monero GUI will try to open the last opened wallet (which is a mainnet wallet) while stagenet is selected, displaying the error below:
![image](https://user-images.githubusercontent.com/45968869/149363744-15ecec2f-2a0d-4f07-8db3-878d953e2afb.png)

**Comment by elibroftw** [comment]
Isn't this just the issue I opened up but in vice versa?

**Comment by d3nd3** [comment]
I can confirm this issue, I have it too.

**Comment by reemuru** [comment]
I just ran into this edge case when I was testing some stuff and jumping between stagenet and mainnet. I opened a [PR](https://github.com/monero-project/monero-gui/pull/3824) that resets the wallet path when changing network type. If user doesn't select new wallet after changing network type and closes they would now be forced back to wallet setup. Selecting the correct wallet file to match network type results in expected behavior.
