### ISSUE TITLE
Double spend even after re-sync following a failed 'pending' tx

### ISSUE THREAD

**Issue by okuh196** [monero-project/monero-gui#3930]
Greetings all.

After an unsuccessful attempt to send money (the transaction received a failed status after several hours of pending status)
I received on the same purse one more transaction and decided to spend money thinking that there could be no problem, but now I receive error 
"Couldn't send the money: transaction <abcd> was rejected by daemon with status: Failed. Reason: double spend"

I saved the old wallet file without the extension and imported the keys after reloading the wallet to have the network scanned from scratch. But the problem remained.

**Comment by VikingBe** [comment]
Advanced mode (Remote node)

**Comment by selsta** [comment]
Closing due to lack of reply.

**Comment by alecov** [comment]
Reopen this. Happened twice to me during the last few weeks.

GUI version: 0.18.3.3-release (Qt 5.15.13)
Embedded Monero version: 0.18.3.3-release
Wallet mode: Advanced mode (Remote node)

Running on Tor over a relatively unstable connection. 

This pops in the log occasionally: `Unable to send transaction(s) to tor - no available outbound connections`.

The first time it happened, the transaction eventually went through and got mined. This _definitely_ proves that "Transaction Failed" is a UX bug: a transaction can _never_ absolutely fail if at least some other node around got hold of it, since nothing guarantees the transaction will not be mined eventually (short of a double-spend transaction).

**Comment by CocolinoFan** [comment]
God bless you @alecov !
Yes! Running `flush_txpool` in the local monerod fixed the issue for me too. 
Wow I was stuck with this for a whole day!
