### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Froggy232** [monero-project/monero-gui#4014]
Hello,
Sorry if it's not the good place, I'm not an expert user of github.
Would it be feasible to have monero-gui run on wayland in place of X11/xwayland?
I have found a thread about it, but it date from 2018, qt visibly wasn't compatible with wayland at that date but it should be now.
Thanks you

**Comment by BigmenPixel0** [comment]
```
flatpak run --env=QT_QPA_PLATFORM=wayland org.getmonero.Monero
```

**Comment by BigmenPixel0** [comment]
You can run it with `QT_QPA_PLATFORM=wayland`.

**Comment by Froggy232** [comment]
Nice, thanks you a lot, it works!
Maybe is it possible to make it the default option? On gnome at least, it uses xwayland.

**Comment by selsta** [comment]
Closing this as the question seems answered by using the env var.

**Comment by q7nm** [comment]
@selsta 
In a pure Wayland session (like in flatpak with --socket=fallback-x11 on Wayland), the application simply [crashes](https://github.com/flathub/org.getmonero.Monero/issues/208). Maybe it's worth making it so that Wayland is used at least when X11 isn't available, or making it the default (it works quite well now)? Of course, in an X11 session, everything should remain the same.

**Comment by selsta** [comment]
@q7nm we plan to make it default in the next release following v0.18.5.0
