### ISSUE TITLE
Settings page could use a "Restore localhost" button

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#542]
I just read a question by a user of the GUI. He had previously connected to a remote node, and was asking about how to restore his GUI settings so it would use his local node. Ideally, there should just be a button that does this automatically.

**Comment by xmr-eric** [comment]
It could also say "Restore default". That might be clearer, perhaps.

**Comment by QuickBASIC** [comment]
It probably would be clearer to have radio buttons to select Remote it Local and allow you to edit the text box only if you select Remote otherwise it uses the default. (Would a local node ever not be localhost with 18018 port?)

It would serve to delineate between using local data and remote data and show for a tooltip [?] that explains what a remote node is and the risks.

**Comment by jonathancross** [comment]
I agree there is a lot of room for improvement here.
* For a local daemon, new users don't need to see "Startup flags", "IP address", port, username or password.
* "Startup flags", "Start daemon" and "Stop daemon" are not applicable to remote.
* "Connect" seems redundant for a local daemon (if you already clicked "Start" it should always connect automatically... well ideally)

I'm considering a few options, but 3 tabs might be good:
1. **Default:** New users should have a very clean interface with only local daemon start / stop option. All local daemon config should be assumed and hidden.  The tab can explain this default state rather than having confusing settings.
2. **Custom local:** More advanced users can customize their local daemon and would look similar to what we now have.  Need to think carefully about what is hidden vs editable here.
3. **Remote:** The final tab for connecting to remote daemon would not have "Startup flags", "Start daemon" and "Stop daemon" buttons.

I'll try to think about this a bit more and create some mock ups.

**Comment by xmr-eric** [comment]
@jonathancross I think @jaqueeee may have addressed this already. I saw something like it in a recent build screenshot someone posted. Jaquee can you confirm?

**Comment by Jaqueeee** [comment]
Yes. I'm remodelling most of this in the remote nodes pr and in the lightwallet Integration I'm currently working on.

**Comment by jonathancross** [comment]
Great to hear!  I'll not bother with mocks then  :-)

**Comment by erciccione** [comment]
+resolved
