### ISSUE TITLE
translate to zh_CN

### ISSUE THREAD

**Issue by zhizhongzhiwai** [monero-project/monero-gui#636]
i'm glad to help translate to zh_CN.
iam from china.

**Comment by JamesCullum** [comment]
Feel free to create a pull request :+1:

**Comment by zhizhongzhiwai** [comment]
ok

**Comment by NanoAkron** [comment]
Hi @zhizhongzhiwai would you care to add a Chinese dictionary wordlist as well so that other Chinese people can use native words to create wallet seeds?

I have found a simplified electrum Chinese wordlist at https://github.com/spesmilo/electrum/tree/master/lib/wordlist

If you could look through and cut it down to 1626 words that are in common usage, then submit a separate pull request, it could be a great help!

All the best!

**Comment by zhizhongzhiwai** [comment]
@NanoAkron 

i'm glad to help.

I am not a c ++ programmer. I do not know how to use these words to generate seed, some question :>

if i look through and cut it down to 1626 words that are in common usage（Make sure there are no duplicate words）, then save the words to file, one word one line.

 is it ok??

which file the world should be save to?

**Comment by dEBRUYNE-1** [comment]
See:

https://github.com/monero-project/monero-gui/blob/master/translations/monero-core_zh-cn.ts

+resolved
