### ISSUE TITLE
[feature request] Simplify display of confirmations

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero-gui#679]
After a transaction receives the suggested 10 confirmations, the user is not left with a clear sense that this is now safe / complete.

It would be nice to see a checkmark (or another visual indicator) marking the tx as "confirmed" with the actual number of confirmations added to the "Transaction Details" modal along with "BlockHeight". Could optionally show the number of confirmations on mouseover.

This would allow us to reduce the noise on the main list by removing "BlockHeight".

Thoughts?

**Comment by medusadigital** [comment]
i like the idea.
also in the same spot is this: https://github.com/monero-project/monero-core/issues/200

so the whole section probably needs a slight redesign. 

having something visual to show the confirmations (maybe in form of a clock that fills up like in bitcoinQT) would sure be nice. 

however, we shouldnt start working on this before having at least some draft of how things should look like. 

if its worth it or if the overall redesign of the whole application should be pushed, that needs to be discussed.

removing blockheight probably wont be possible, since the main sorting is happening there (and the timestamp cant be used)

**Comment by jonathancross** [comment]
> having something visual to show the confirmations...

Yeah, this would be great.

> removing blockheight probably wont be possible, since the main sorting is happening there (and the timestamp cant be used)

Good point.  But why can't the timestamp be used?

**Comment by medusadigital** [comment]
> Good point. But why can't the timestamp be used?

becasue timestamps are set by the miners and can be slightly off:

![timestamps](https://cloud.githubusercontent.com/assets/17108301/25229288/f37b16ec-25cf-11e7-9171-3a03311b0460.png)


also its much easier to test, since the same default sorting applies in the CLI wallet. 

also, we just had issues with the sorting in the past and just chose the easy route due to time pressure: https://github.com/mbg033/monero-core/issues/70

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by jonathancross** [comment]
Thanks for explaining @medusadigital... strange that times they can be so far off.
I need to research how a miner can set a UTC timestamp that is **_earlier_** than the previous block.  I'd expect this to be rejected.

**Comment by selsta** [comment]
The history page looks like this now:

<img width="1092" alt="Screenshot 2019-04-27 at 01 59 34" src="https://user-images.githubusercontent.com/7697454/56841777-1cd7e100-6890-11e9-8d06-5e05355f276f.png">

@jonathancross Do you consider this resolved?

**Comment by jonathancross** [comment]
Yes, thanks!
