### ISSUE TITLE
[Feature Request] Uri scheme for Monero Core

### ISSUE THREAD

**Issue by serhack** [monero-project/monero-gui#760]
Hello,
I'm developing integrations for Monero. I think I can include in checkout page a button that open monero-gui with address-field precompiled. This should a good idea, then the client can click with a button :)
For this, we need uri scheme support.
I can provide some resources about how to develop this 
Windows : https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx

**Comment by amiuhle** [comment]
`monero-wallet-rpc` already generates URIs in the form `monero:<address>?tx_amount=1`:

https://getmonero.org/knowledge-base/developer-guides/wallet-rpc#makeuri

Just pointing this out as it might help you with your integrations, it'll still have to be implemented in GUI clients, of course.

**Comment by serhack** [comment]
@amiuhle Sorry for lately answer. Thanks for resource!

**Comment by dEBRUYNE-1** [comment]
+feature

**Comment by alvinjoelsantos** [comment]
+feature

**Comment by pazos** [comment]
I'm working on this and think it is easy to implement for osx/ios, because it is just add a string to Info.plist and the computer will register the application itself. For linux seems easy doable too but we need a desktop file to be able to use xdg-open.

When I have some time to wrap the code together and tested on mac/linux I'll ping you @serhack to find a way to do it without messing too much with m$ registry
