### ISSUE TITLE
Standard wallet location (Linux)

### ISSUE THREAD

**Issue by SleepingShell** [monero-project/monero-gui#795]
Currently, the CLI and GUI create wallets in a different manor.

Program | Location
------------|------------
CLI | Same folder as binary
GUI | ~/Monero

I believe there should be a standard between the two implementations. After I created my wallet in the GUI and tried to use the wallet-cli tool, I had to specify the full path. This is not much of a problem, but there should either be a standard to create wallets in the same folder, or have the GUI and CLI check for wallets in the default location for the other program.

Perhaps a wallet subdirectory in the same dir as the binaries would make sense, since these binaries are in the same directory when doing a default install. Additionally, there are already different folders such as plugins, qml, etc.

The .bitmonero folder would also be a good contender, as that would not depend upon the location of the binaries. Additionally, this would follow the standard most other blockchains use such as Bitcoin and Ethereum with keeping the wallet file in the same directory structure as the blockchain itself.

**Comment by Jaqueeee** [comment]
Storing in same folder as binaries is tricky because it's easy to delete them by accident when upgrading. Also, on Mac it wouldn't make sense because the binaries are embedded in a DMG-file that average users never opens. 

.bitmonero could work on Linux and Mac but not on windows where blockchain is stored in `C:\ProgramData\bitmonero`. I.e outside the users home folder.  I prefer the current setup over that. 

Good idea to make cli wallet more aware of the wallet paths used by the GUI. Maybe you could open an issue in the cli rep for this?

+wontfix

**Comment by Jaqueeee** [comment]
testing the new labeling system. didn't mean to close this issue. Will be opened again shortly :)

**Comment by medusadigital** [comment]
seems it doesnt open again even if the label is removed

**Comment by danrmiller** [comment]
to re-open you tell the bot to remove the label, don't remove the command you gave to add the label.

-wontfix

**Comment by skftn** [comment]
+enhancement

**Comment by mmbyday** [comment]
Soon the wallet will be encrypted by default and stored in the lmdb database.
Won't be an issue then.
+resolved

**Comment by dEBRUYNE-1** [comment]
+resolved
