### ISSUE TITLE
Wallet crash on OSX when switching to a different and invalid remote node while syncing

### ISSUE THREAD

**Issue by jedigras** [monero-project/monero-gui#804]
The GUI wallet crashed when I was syncing using one of my remote nodes.  I decided to try to spin up a windows remote node too and connect to that from the GUI while it was still syncing using the first linux remote node.  It just hung and crashed.  I later realized that the windows node wasn't even accessible remotely as the port was firewalled off.  I guess some more robust error checking or something to disconnect the connected remote node would be nice.

**Comment by medusadigital** [comment]
i agree on the more robust error checking when connecting, would be a good idea to make that more solid.

what i fear is that this might be the wrong repo, since this is probably something affecting the wallet APi directly, which is part of monero itself.

@Jaqueeee knows the code well, what do you think? 

or any chances its a monero-core related thing ?

**Comment by erciccione** [comment]
Can be reopened if valid

+invalid
