### ISSUE TITLE
remove sign/verify feature from monero-core Desktop version

### ISSUE THREAD

**Issue by medusadigital** [monero-project/monero-gui#810]
since this is also missing on the mobile version, it would just be consequent.

also i do not think that feature is in use, besides being cool.

it may additionally help free up some space.

other opinions very welcome. 

related too (something we wouldnt need to do) : https://github.com/monero-project/monero-core/issues/174

**Comment by danrmiller** [comment]
NACK. I don't know how to argue for its importance or back it up, other than my opinion and that I like it.

**Comment by Ashaman-** [comment]
This is a terrible idea. Just one use case that it breaks: Monero pools generally don't have an account you sign up for - your account is your XMR address. If you were to ever need to contact your pool for any kind of technical support, literally the only way you can prove who you are to the pool operator is with a signed message. And the reduction in size of the application that might come from removal of this features would be absolutely negligible because the libraries it uses is cannot be removed since they are the same ones used for constructing and verifying transactions.

**Comment by mmbyday** [comment]
+resolved

**Comment by dEBRUYNE-1** [comment]
As far as I know, the rough consensus is to keep this feature in advanced mode. I, therefore, am going to close this issue.

**Comment by dEBRUYNE-1** [comment]
+resolved
