### ISSUE TITLE
MacOS GUI turn on dedicated graphics card

### ISSUE THREAD

**Issue by Axam** [monero-project/monero-gui#829]
MacOS GUI Beta 2 always turn on dedicated graphics card on MacBooks with switchable graphics.
Such behavior isn't power efficient. Is it possible to remove dGPU dependency?

**Comment by johnalanwoods** [comment]
Is this issue still occurring on the release GUI? I'd guess so, but don't have a Mac with dual cards to test.

This issue can be solved by including 'NSSupportsAutomaticGraphicsSwitching' in the info.plist appropriately, and is compatible with all Mac OS releases since 10.7 (2011)

Further considerations here: https://developer.apple.com/library/content/technotes/tn2229/_index.html

**Comment by Tech-CF** [comment]
Still an issue with 0.11.1.0 the monero-wallet-gui.app is still listed as "Requires High Perf GPU" in the Activity Monitor under Energy.

**Comment by skftn** [comment]
Was previously fixed via #1367. Thanks for the heads-up.

+resolved
